"""add_completion_confirmations

Revision ID: a7ebfa866f81
Revises: f741c7de96fd
Create Date: 2026-06-05 12:41:41.821911+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a7ebfa866f81'
down_revision: Union[str, None] = 'f741c7de96fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completion_confirmations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transfusion_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', postgresql.ENUM('patient', 'donor', 'coordinator', 'hospital', name='confirmationrole', create_type=False), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'confirmed', 'rejected', 'timeout', 'overridden', name='confirmationstatus', create_type=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transfusion_id'], ['transfusions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_completion_confirmations_transfusion_id'), 'completion_confirmations', ['transfusion_id'], unique=False)
    op.create_index(op.f('ix_completion_confirmations_user_id'), 'completion_confirmations', ['user_id'], unique=False)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    op.drop_index(op.f('ix_completion_confirmations_user_id'), table_name='completion_confirmations')
    op.drop_index(op.f('ix_completion_confirmations_transfusion_id'), table_name='completion_confirmations')
    op.drop_table('completion_confirmations')
    # ### end Alembic commands ###
