"""initial migration

Revision ID: f741c7de96fd
Revises: 
Create Date: 2026-06-03 18:06:06.903365+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f741c7de96fd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('patient', 'donor', 'coordinator', 'hospital', 'admin', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('coordinators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('assigned_region', sa.String(length=255), nullable=True),
    sa.Column('approval_status', sa.Enum('pending', 'approved', 'rejected', name='approvalstatus'), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('donors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender'), nullable=False),
    sa.Column('blood_group', sa.Enum('A_POS', 'A_NEG', 'B_POS', 'B_NEG', 'AB_POS', 'AB_NEG', 'O_POS', 'O_NEG', name='bloodgroup'), nullable=False),
    sa.Column('last_donation_date', sa.Date(), nullable=True),
    sa.Column('total_donations', sa.Integer(), nullable=False),
    sa.Column('preferred_days', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferred_times', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('max_travel_distance_km', sa.Integer(), nullable=False),
    sa.Column('communication_preference', sa.Enum('whatsapp', 'sms', name='communicationpreference'), nullable=True),
    sa.Column('language_preference', sa.Enum('en', 'hi', name='language'), nullable=True),
    sa.Column('upi_id', sa.String(length=100), nullable=True),
    sa.Column('reliability_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('age >= 18', name='ck_donors_age_min_18'),
    sa.CheckConstraint('max_travel_distance_km > 0', name='ck_donors_distance_positive'),
    sa.CheckConstraint('reliability_score >= 0 AND reliability_score <= 100', name='ck_donors_reliability_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('hospitals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('total_transfusion_beds', sa.Integer(), nullable=False),
    sa.Column('total_transfusion_chairs', sa.Integer(), nullable=False),
    sa.Column('emergency_capacity', sa.Integer(), nullable=False),
    sa.Column('coordinator_name', sa.String(length=255), nullable=True),
    sa.Column('coordinator_email', sa.String(length=255), nullable=True),
    sa.Column('coordinator_phone', sa.String(length=20), nullable=True),
    sa.Column('operating_hours_start', sa.Time(), nullable=True),
    sa.Column('operating_hours_end', sa.Time(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('emergency_capacity >= 0', name='ck_hospitals_emergency_non_negative'),
    sa.CheckConstraint('total_transfusion_beds >= 0', name='ck_hospitals_beds_non_negative'),
    sa.CheckConstraint('total_transfusion_chairs >= 0', name='ck_hospitals_chairs_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_hospitals_city'), 'hospitals', ['city'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('matching_failure', 'prediction_failure', 'notification_failure', 'hospital_sync_failure', 'wallet_failure', 'system_error', 'security', 'escalation', name='incidenttype'), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='incidentseverity'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('component', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('open', 'investigating', 'resolved', 'closed', name='incidentstatus'), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender'), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('blood_group', sa.Enum('A_POS', 'A_NEG', 'B_POS', 'B_NEG', 'AB_POS', 'AB_NEG', 'O_POS', 'O_NEG', name='bloodgroup'), nullable=False),
    sa.Column('thalassemia_type', sa.Enum('major', 'intermedia', 'minor', 'hb_e', 'hb_s', name='thalassemiatype'), nullable=False),
    sa.Column('last_transfusion_date', sa.Date(), nullable=True),
    sa.Column('avg_transfusion_interval_days', sa.Integer(), nullable=False),
    sa.Column('emergency_contact_name', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('data_sharing_consent', sa.Boolean(), nullable=False),
    sa.Column('emergency_consent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('age > 0', name='ck_patients_age_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_earned', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_spent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('balance >= 0', name='ck_wallets_balance_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('friendship_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('donor_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_donations', sa.Integer(), nullable=False),
    sa.Column('relationship_duration_days', sa.Integer(), nullable=False),
    sa.Column('positive_interactions', sa.Integer(), nullable=False),
    sa.Column('negative_interactions', sa.Integer(), nullable=False),
    sa.Column('last_interaction_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='ck_friendship_score_range'),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'donor_id', name='uq_friendship_patient_donor')
    )
    op.create_index(op.f('ix_friendship_scores_donor_id'), 'friendship_scores', ['donor_id'], unique=False)
    op.create_index(op.f('ix_friendship_scores_patient_id'), 'friendship_scores', ['patient_id'], unique=False)
    op.create_table('hospital_capacities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('available_beds', sa.Integer(), nullable=False),
    sa.Column('occupied_beds', sa.Integer(), nullable=False),
    sa.Column('available_chairs', sa.Integer(), nullable=False),
    sa.Column('occupied_chairs', sa.Integer(), nullable=False),
    sa.Column('staff_available', sa.Integer(), nullable=False),
    sa.Column('upcoming_appointments', sa.Integer(), nullable=False),
    sa.Column('emergency_capacity_available', sa.Integer(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('available_beds >= 0', name='ck_hospital_cap_avail_beds_non_neg'),
    sa.CheckConstraint('available_chairs >= 0', name='ck_hospital_cap_avail_chairs_non_neg'),
    sa.CheckConstraint('occupied_beds >= 0', name='ck_hospital_cap_occ_beds_non_neg'),
    sa.CheckConstraint('occupied_chairs >= 0', name='ck_hospital_cap_occ_chairs_non_neg'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id')
    )
    op.create_table('patient_hospital_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('preference_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('preference_order >= 1 AND preference_order <= 3', name='ck_pref_order_range'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'hospital_id', name='uq_patient_hospital'),
    sa.UniqueConstraint('patient_id', 'preference_order', name='uq_patient_pref_order')
    )
    op.create_table('transfusions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('donor_id', sa.UUID(), nullable=True),
    sa.Column('hospital_id', sa.UUID(), nullable=True),
    sa.Column('coordinator_id', sa.UUID(), nullable=True),
    sa.Column('predicted_date', sa.Date(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('urgency_level', sa.Enum('routine', 'urgent', 'emergency', name='urgencylevel'), nullable=False),
    sa.Column('status', sa.Enum('predicted', 'patient_confirmed', 'matching_donors', 'donor_confirmed', 'coordinator_confirmed', 'hospital_confirmed', 'scheduled', 'in_progress', 'completed', 'cancelled', 'failed', name='transfusionstatus'), nullable=False),
    sa.Column('patient_confirmation', sa.Enum('pending', 'confirmed', 'modified', 'rejected', name='patientconfirmation'), nullable=False),
    sa.Column('donor_confirmation', sa.Enum('pending', 'confirmed', 'rejected', 'timeout', name='donorconfirmation'), nullable=False),
    sa.Column('coordinator_confirmation', sa.Enum('pending', 'confirmed', 'overridden', name='coordinatorconfirmation'), nullable=False),
    sa.Column('hospital_confirmation', sa.Enum('pending', 'confirmed', 'rejected', 'unavailable', name='hospitalconfirmation'), nullable=False),
    sa.Column('is_emergency', sa.Boolean(), nullable=False),
    sa.Column('emergency_reason', sa.String(length=500), nullable=True),
    sa.Column('alternate_hospital_id', sa.UUID(), nullable=True),
    sa.Column('previous_donor_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alternate_hospital_id'], ['hospitals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['coordinator_id'], ['coordinators.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_donor_id'], ['donors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfusions_status'), 'transfusions', ['status'], unique=False)
    op.create_table('wallet_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('credit', 'debit', name='transactiontype'), nullable=False),
    sa.Column('category', sa.Enum('reward_conversion', 'reimbursement', 'expense_payment', 'assistance', 'withdrawal', 'correction', name='transactioncategory'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', 'reversed', name='transactionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_wallet_txn_amount_positive'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_transactions_wallet_id'), 'wallet_transactions', ['wallet_id'], unique=False)
    op.create_table('confirmations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transfusion_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('patient', 'donor', 'coordinator', 'hospital', name='confirmationrole'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'rejected', 'timeout', 'overridden', name='confirmationstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reminder_count', sa.Integer(), nullable=False),
    sa.Column('last_reminder_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transfusion_id'], ['transfusions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_confirmations_transfusion_id'), 'confirmations', ['transfusion_id'], unique=False)
    op.create_index(op.f('ix_confirmations_user_id'), 'confirmations', ['user_id'], unique=False)
    op.create_table('donations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transfusion_id', sa.UUID(), nullable=False),
    sa.Column('donor_id', sa.UUID(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('donation_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'completed', 'cancelled', 'no_show', name='donationstatus'), nullable=False),
    sa.Column('blood_units', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transfusion_id'], ['transfusions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donations_donor_id'), 'donations', ['donor_id'], unique=False)
    op.create_index(op.f('ix_donations_transfusion_id'), 'donations', ['transfusion_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('transfusion_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('donation_request', 'reminder', 'emergency_alert', 'confirmation_request', 'follow_up', 'system', 'reward', 'expense', name='notificationtype'), nullable=False),
    sa.Column('channel', sa.Enum('app', 'whatsapp', 'sms', name='notificationchannel'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('language', sa.Enum('en', 'hi', name='language'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'normal', 'high', 'emergency', name='notificationpriority'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'delivered', 'failed', 'read', name='notificationstatus'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transfusion_id'], ['transfusions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_transfusion_id'), 'notifications', ['transfusion_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('expense_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('donation_id', sa.UUID(), nullable=False),
    sa.Column('donor_id', sa.UUID(), nullable=False),
    sa.Column('travel_expense', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('other_expense', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'flagged', 'rejected', name='expensestatus'), nullable=False),
    sa.Column('is_flagged_by_ai', sa.Boolean(), nullable=False),
    sa.Column('flag_reason', sa.String(length=500), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('other_expense >= 0', name='ck_expense_other_non_negative'),
    sa.CheckConstraint('travel_expense >= 0', name='ck_expense_travel_non_negative'),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_requests_donation_id'), 'expense_requests', ['donation_id'], unique=False)
    op.create_index(op.f('ix_expense_requests_donor_id'), 'expense_requests', ['donor_id'], unique=False)
    op.create_table('rewards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('donor_id', sa.UUID(), nullable=False),
    sa.Column('donation_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('donation', 'emergency_donation', 'consistency_bonus', 'rare_blood_group', 'referral', 'milestone', name='rewardtype'), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('points > 0', name='ck_rewards_points_positive'),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rewards_donor_id'), 'rewards', ['donor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rewards_donor_id'), table_name='rewards')
    op.drop_table('rewards')
    op.drop_index(op.f('ix_expense_requests_donor_id'), table_name='expense_requests')
    op.drop_index(op.f('ix_expense_requests_donation_id'), table_name='expense_requests')
    op.drop_table('expense_requests')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_transfusion_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_donations_transfusion_id'), table_name='donations')
    op.drop_index(op.f('ix_donations_donor_id'), table_name='donations')
    op.drop_table('donations')
    op.drop_index(op.f('ix_confirmations_user_id'), table_name='confirmations')
    op.drop_index(op.f('ix_confirmations_transfusion_id'), table_name='confirmations')
    op.drop_table('confirmations')
    op.drop_index(op.f('ix_wallet_transactions_wallet_id'), table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index(op.f('ix_transfusions_status'), table_name='transfusions')
    op.drop_table('transfusions')
    op.drop_table('patient_hospital_preferences')
    op.drop_table('hospital_capacities')
    op.drop_index(op.f('ix_friendship_scores_patient_id'), table_name='friendship_scores')
    op.drop_index(op.f('ix_friendship_scores_donor_id'), table_name='friendship_scores')
    op.drop_table('friendship_scores')
    op.drop_table('wallets')
    op.drop_table('patients')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_hospitals_city'), table_name='hospitals')
    op.drop_table('hospitals')
    op.drop_table('donors')
    op.drop_table('coordinators')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
