"""add_missing_donor_columns

Revision ID: 3b17b226578e
Revises: a7ebfa866f81
Create Date: 2026-06-05 19:17:15.181817+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b17b226578e'
down_revision: Union[str, None] = 'a7ebfa866f81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donors', sa.Column('medical_clearance_url', sa.String(length=500), nullable=True))
    op.add_column('donors', sa.Column('medical_clearance_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('donors', sa.Column('demanded_reimbursement', sa.Numeric(precision=10, scale=2), nullable=False))
    op.drop_constraint('expense_requests_donation_id_fkey', 'expense_requests', type_='foreignkey')
    op.create_foreign_key(None, 'expense_requests', 'transfusions', ['donation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expense_requests', type_='foreignkey')
    op.create_foreign_key('expense_requests_donation_id_fkey', 'expense_requests', 'donations', ['donation_id'], ['id'], ondelete='CASCADE')
    op.drop_column('donors', 'demanded_reimbursement')
    op.drop_column('donors', 'medical_clearance_at')
    op.drop_column('donors', 'medical_clearance_url')
    # ### end Alembic commands ###
